apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "133ecd920cfc0667389d9fd5c73f3a803ce876a5"
        buildDate: "20220212175734"
    spec:
      containers:
        - name: products
          image: cyb3rp4ul3y/products:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockersecret
