apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "514639d6788a0de66663c390c36209f9484b1eb7"
        buildDate: "20220218210905"
    spec:
      containers:
        - name: products
          image: cyb3rp4ul3y/products:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockersecret
