apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "f15d8e9847fd5d9581251a6f19d33596ea3cc3c5"
        buildDate: "20220212141442"
    spec:
      containers:
        - name: products
          image: localhost:5000/products:latest
          ports:
            - containerPort: 8080
              name: 8080-tcp
