apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "8e92d52eca282fe6948cc1caba86ffe14dfb8ce0"
        buildDate: "20220212142517"
    spec:
      containers:
        - name: products
          image: cyb3rp4ul3y/products:latest
          ports:
            - containerPort: 8080
              name: 8080-tcp
