apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "136717bb71788a1d9bf4bc4d950e43aa1d08aab1"
        buildDate: "20220218201003"
    spec:
      containers:
        - name: products
          image: cyb3rp4ul3y/products:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockersecret
