apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "a340c2adef7f20d526d1c2294e3f0a208f019c8d"
        buildDate: "20220222004008"
    spec:
      containers:
        - name: products
          image: cyb3rp4ul3y/products:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockersecret
