apiVersion: v1
kind: Secret
metadata:
  name: git-auth
  namespace: tekton-poc
  annotations:
    tekton.dev/git-0: https://github.com/
type: kubernetes.io/basic-auth
stringData:
  username: ## INSERTAR TOKEN AQUÍ
  password: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-push-service-account
  namespace: tekton-poc
secrets:
  - name: git-auth