apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  name: repo-gitops
  namespace: cicd
type: Opaque
stringData:
  username: "7c97050704cdd6d7272ea64a59f955e521e715fa"
  password: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: cicd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/jaruizes/tekton-argocd-poc
      passwordSecret:
        name: repo-gitops
        key: password
      usernameSecret:
        name: repo-gitops
        key: username
