apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  name: repo-gitops
  namespace: argocd
type: Opaque
stringData:
  username: tekton
  password: d20f10568f4e84495235df6b0625545426946c5b
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/jaruizes/tekton-argocd-poc
      passwordSecret:
        name: repo-gitops
        key: password
      usernameSecret:
        name: repo-gitops
        key: username